baseurl = "https://gracious-ride-adae32.netlify.com"
languageCode = "en-us"
title = "Words"
theme=  "anubis"

[params]
   author = "SP"
   description = "Anubis is a simple minimalist theme for Hugo blog engine."